version: '3'
services:
  api:
    image: express-workout-tracker-api
    container_name: api
    build: .
    networks:
      - backend
    links:
      - mongodb
    ports:
      - '3000:3000' # express server
      - '9229:9229' # nodemon debugger
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    restart: always
    depends_on:
      - mongodb
    #command: npm run dev

  mongodb:
    image: mongo
    container_name: mongodb
    env_file: .env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - backend
    command: mongod --auth

  # Web-based MongoDB admin interface
  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: true
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongodb

networks:
  backend:
    name: express-workout-tracker-api-network
    driver: bridge

volumes:
  data:
