version: '3'
services:
  api:
    image: express-workout-tracker-api
    build: .
    networks:
      - backend
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    restart: always
    #command: npm run dev

networks:
  backend:
    driver: bridge
